# -*- coding: utf-8 -*-
"""Z5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYBe-4FMCYSqU0Kr1likdfxeYxwt39P9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Generate  data for global GDP
years = range(2000, 2021)
countries = ['United States', 'China', 'Japan', 'Germany', 'India']
gdp_data = np.random.uniform(1000, 5000, (len(years), len(countries)))
gdp_df = pd.DataFrame(gdp_data, index=years, columns=countries)

# Summary Statistics
gdp_summary_stats = gdp_df.describe().loc[['mean', 'std', 'min', 'max']]

# Plot 1: Average GDP for Each Country Over Time (Bar Plot)
plt.figure(figsize=(12, 8))
gdp_df.mean().plot(kind='bar', color='skyblue')
plt.title('Average GDP for Each Country Over Time')
plt.xlabel('Country')
plt.ylabel('Average GDP (Billions of USD)')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.savefig('average_gdp_for_each_country_bar.png')
plt.show()

# Plot 2: Total GDP Over Time (Line Plot)
plt.figure(figsize=(12, 8))
plt.plot(gdp_df.index, gdp_df.sum(axis=1), marker='o', color='salmon')
plt.title('Total GDP Over Time')
plt.xlabel('Year')
plt.ylabel('Total GDP (Billions of USD)')
plt.grid(True)
plt.savefig('total_gdp_over_time_line.png')
plt.show()

# Summary Statistics Table
gdp_summary_stats.to_csv('summary_statistics_global_gdp.csv')

# Print Summary Statistics
print(gdp_summary_stats)